### PR TITLE
github: add the "refresh" workflow

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Comment by Saviq** [comment]
@AlanGriffiths this can be seen in action here:

https://github.com/Saviq/iot-example-graphical-snap/actions/runs/3948716131

**Comment by Saviq** [comment]
When this fails, the committer to `main` will get notified, so we can deal then with e.g. conflicts.

I _could_ also run this on pull requests so we get early feedback?

**Comment by AlanGriffiths** [comment]
Ideally, we'd also check that the branch builds and runs correctly before pushing.

**Comment by Saviq** [comment]
Replaced by #16.

**Pull request closed without merging**
